clc;
clear;
data = readtable('C:\Users\28022\Desktop\question_4_q.xlsx');
time_20s = datetime(data.("time_20s_"), 'InputFormat', 'yyyy-MM-dd HH:mm:ss');
q_20s = data.("x20s");
time_5min = datetime(data.("time_5min_"), 'InputFormat', 'yyyy-MM-dd HH:mm:ss.SSS'); 
q_5min = data.("x5min"); 
time_15min = datetime(data.("time_15min_"), 'InputFormat', 'yyyy-MM-dd HH:mm:ss'); 
q_15min = data.("x15min"); 
figure;
scatter(time_20s, q_20s, 2, 'b', 'filled'); 
hold on;
plot(time_5min, q_5min, 'r-o', 'LineWidth', 0.8, 'MarkerSize', 2); 
plot(time_15min, q_15min, 'g-s', 'LineWidth', 1, 'MarkerSize', 2);
legend({'20秒周期散点', '5分钟周期曲线', '15分钟周期曲线'}, 'FontSize', 12, 'Location', 'northwest');
xlabel('时间 (时:分:秒)', 'Interpreter', 'latex', 'FontSize', 14);
ylabel('流量 (q)', 'Interpreter', 'latex', 'FontSize', 14);
ax = gca;
datetick('x','HH:MM:SS','keepticks');
ax.XTickLabelRotation = 45; 
ax.FontSize = 12;
ax.LineWidth = 1.5; 
grid on;
set(gca, 'GridLineStyle', '--', 'GridColor', 'k', 'GridAlpha', 0.2);
set(gca, 'Box', 'on'); 
set(gcf, 'Position', [100, 100, 1200, 800]); 
set(gca, 'FontWeight', 'bold');
hold off;
